### ISSUE TITLE
Your research is very interesting. Could you please share the complete code for academic communication?

### ISSUE THREAD

**Issue by helen-hanjia** [xmed-lab/FoPro-KD#1]

**Comment by marwankefah** [comment]
Hi Helen,

Thank you for expressing interest in our work.

Currently, we do not plan to share the ``FPG`` module, as our algorithm development is still ongoing. For comparing and reproducing purposes on the ``5-fold long-tailed split`` provided [here](https://github.com/xmed-lab/FoPro-KD/tree/main/data/ham2019), we offer the implementation of our ``EKD`` in [FedMAS](https://github.com/xmed-lab/Fed-MAS/) designed for effective knowledge distillation. Operating [FedMAS](https://github.com/xmed-lab/Fed-MAS/) with ``client_num=1`` is intended to mirror the execution of Effective Knowledge Distillation (EKD) presented in our FoPro-KD paper.

Should you have any questions or need further clarification, please do not hesitate to ask me.

Thank you in advance,

Warm regards,

Marawan Elbatel
