### ISSUE TITLE
Code Release？

### ISSUE THREAD

**Issue by Jacky-H-uang** [xmed-lab/FoPro-KD#2]
Your research is so excellent, can you release the code？

**Comment by marwankefah** [comment]
Hi Jacky, 

Thank you for expressing interest in our work. 

For comparing and reproducing purposes on the 5-fold long-tailed split provided [here](https://github.com/xmed-lab/FoPro-KD/tree/main/data/ham2019), we offer the implementation of our EKD in [FedMAS](https://github.com/xmed-lab/Fed-MAS) designed for effective knowledge distillation. Operating [FedMAS](https://github.com/xmed-lab/Fed-MAS) with client_num=1 is intended to mirror the execution of Effective Knowledge Distillation (EKD) presented in our FoPro-KD paper. Currently, we do not plan to share the FPG module.

Should you have any questions or need further clarification, please do not hesitate to ask me. 

Thank you in advance, 

Warm regards, 
Marawan Elbatel
